name: CI/CD to Azure App Service - Spring Boot Gradle

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: spring-gradle-app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: build/libs/*.jar
