name: Build and deploy JAR app to Azure Web App - spring-gradle-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew  # ✅ Making gradlew executable

      - name: Build with Gradle
        run: ./gradlew build --no-daemon  # ✅ Building using Gradle

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          # path: '${{ github.workspace }}/build/libs/*.jar'  # ✅ Upload any jar in build/libs
          path: 'build/libs/spring-gradle-app-0.0.1-SNAPSHOT.jar'


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'spring-gradle-app'
          slot-name: 'Production'
          # package: '*.jar'  # ✅ Wildcard used to avoid path mismatch
          package: 'build/libs/spring-gradle-app-0.0.1-SNAPSHOT.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5E7CD5A6719B4611973313BAF78286BE }}
